### ISSUE TITLE
[ERROR]:Error in AdaRank::load():

### ISSUE THREAD

**Issue by Gu-Youngfeng** [Gu-Youngfeng/ReConfigSRC#5]
Last commit a62edaf solved the issue #4 successfully, but it simultaneously triggered another error when running `reconfig.py` using ranker **AdaRank**, look at the following failing trace,

```python
Discard orig. features
Model file:     trainer.txt
Feature normalization: No
Model:          AdaRank
Exception in thread "main" ciir.umass.edu.utilities.RankLibError: Error in AdaRank::load():
        at ciir.umass.edu.utilities.RankLibError.create(RankLibError.java:34)
        at ciir.umass.edu.learning.boosting.AdaRank.loadFromString(AdaRank.java:347)
        at ciir.umass.edu.learning.RankerFactory.loadRankerFromString(RankerFactory.java:109)
        at ciir.umass.edu.learning.RankerFactory.loadRankerFromFile(RankerFactory.java:99)
        at ciir.umass.edu.eval.Evaluator.rank(Evaluator.java:1258)
        at ciir.umass.edu.eval.Evaluator.main(Evaluator.java:527)
Caused by: java.lang.NullPointerException
        at ciir.umass.edu.learning.boosting.AdaRank.loadFromString(AdaRank.java:333)
        ... 4 more
```

There is a possibility that some parameters in **AdaRank** are mis-assignmented. Here are the commands we used to invoke ranker **AdaRank**. The error happened when running _command 2_.

_Command 1_: Training a model `trainer.txt` based on `trainset_txt15.txt`.
```python
>> java -jar RankLib.jar -train trainset_txt15.txt -ranker 3 -metric2t ERR@10 -round 500 -tolerance 0.002 -max 5 -save trainer.txt
```
_Command 2_: Re-ranking the `testset_txt15.txt` based on `trainer.txt`, then save the results in `result.txt`
```python
>> java -jar RankLib.jar -rank testset_txt15.txt -load trainer.txt -indri result.txt
```

**Comment by Gu-Youngfeng** [comment]
After tried many times to tune the parameters, I found that if I change the `-metric2t ERR@10` to `-metric2t NDCG@10`, the above error will be clear. **However, the re-ranked list is the same with the original list.** That is, **AdaRank** CANNOT change the relative order of configurations in the original list.

**Comment by Gu-Youngfeng** [comment]
Maybe all the metrics to be optimized in a learning-to-rank model should be set to `-metric2t NDCG@k`. That is, the _command 1_ should be,

```python
>> java -jar RankLib.jar -train train_set.txt -ranker XX -metric NDCG@10 -save trainer.txt
```
